extra:
  pagetime: 'on'
  search:
    language: cn
extra_css:
- from_oi_wiki/css/extra.css?v=13
extra_javascript:
- from_oi_wiki/js/extra.js?v=16
- js/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
google_analytics:
- UA-247073947-1
- auto
plugins:
- search
- callouts
markdown_extensions:
- nl2br
- admonition
- pymdownx.details
- pymdownx.superfences
- toc:
    permalink: true
    slugify: !!python/name:pymdownx.slugs.uslugify ''
- admonition
- abbr
- attr_list
- def_list
- footnotes
- meta
- md_in_html
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
    emoji_index: !!python/name:materialx.emoji.twemoji ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink:
    repo: mkdocs-material
    repo_url_shorthand: true
    user: squidfunk
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
      name: mermaid
- pymdownx.tabbed
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- RABBIT:
  - ME: index.md
- ALGO:
  - ALGO: posts/ALGO/index.md
  - MST_survey: posts/ALGO/MST_survey.md
  - Competitive_Contest:
    - KMP: posts/ALGO/Competitive_Contest/KMP.md
    - Minimize_The_Number_of_Swaps_to_Sort_List: posts/ALGO/Competitive_Contest/Minimize_The_Number_of_Swaps_to_Sort_List.md
- Crypto:
  - Crypto: posts/Crypto/index.md
  - RSA: posts/Crypto/RSA.md
- MATH:
  - MATH: posts/MATH/index.md
  - FFT: posts/MATH/FFT.md
  - Combinatorial_Maths:
    - Burnside's_Lemma: posts/MATH/Combinatorial_Maths/Burnside's_Lemma.md
  - MISCS:
    - "\u8FDE\u7EED, \u65B9\u5411\u5BFC\u6570\u90FD\u5B58\u5728\u4F46\u4E0D\u53EF\u5FAE": "posts/MATH/MISCS/\u8FDE\
        \u7EED, \u65B9\u5411\u5BFC\u6570\u90FD\u5B58\u5728\u4F46\u4E0D\u53EF\u5FAE\
        .md"
- CPP:
  - CPP: posts/CPP/index.md
  - CRTP: posts/CPP/CRTP.md
  - UB:
    - infinite_loop: posts/CPP/UB/infinite_loop.md
- "\u5173\u4E8E":
  - "\u5173\u4E8E": "posts/\u5173\u4E8E/index.md"
  - Courses_Discription: "posts/\u5173\u4E8E/Courses_Discription.md"
repo_name: 27rabbitlt pages
repo_url: https://github.com/27rabbitlt/27rabbitlt.github.io
site_name: RABBIT HOLE
site_url: https://27rabbitlt.github.io/
theme:
  custom_dir: overrides
  favicon: asset/black_circle_rabbit.png
  features:
  - navigation.tabs
  font:
    code: Fira Mono
    text: Fira Sans
  language: en
  logo: asset/black_circle_rabbit.png
  name: material
  palette:
    primary: black
    scheme: default
